development:
  - 'your_name@gmail.com'
ps4_friends:
  - 'friend_01@gmail.com'
  - 'friend_02@gmail.com'
  - 'friend_03@gmail.com'
  - 'friend_04@gmail.com'
  - 'friend_05@gmail.com'
3ds_friends:
  - 'friend_06@gmail.com'
  - 'friend_07@gmail.com'
  - 'friend_08@gmail.com'
  - 'friend_09@gmail.com'
  - 'friend_10@gmail.com'
vita_friends:
  - 'friend_11@gmail.com'
  - 'friend_12@gmail.com'
  - 'friend_13@gmail.com'
  - 'friend_14@gmail.com'
  - 'friend_15@gmail.com'
switch_friends:
  - 'friend_16@gmail.com'
  - 'friend_17@gmail.com'
  - 'friend_18@gmail.com'
  - 'friend_19@gmail.com'
  - 'friend_20@gmail.com'
